### PR TITLE
​

### LINKED ISSUE #427: Leaderboard fix for protocol v11
Leaderboard packet looks like the same, only without 'isme' flag. So its just a list of string.
New packet with id '48' looks like.
Uint8 opcode
Uint16 my position

Right now i dont know how it changes if you are in top 10.

EDIT: packet 0x30 (aka 48) is sent right after every leaderboard packet. It contains the position of player in leaderboard and its sent when player is joined to game (not sent when dead or spectating).

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by cowpits** [comment]
thank you so much, works!!!

**Comment by PrinceDark9243** [comment]
it works but donset show that light red color on my nick on leaderboard

**Comment by cowpits** [comment]
yes as PrinceDark9243 said but i'm happy with it for now

**Comment by NuclearC** [comment]
lol i could fix it but idk NodeJS much so my code would look like shit

**Comment by AlexandriteErikParacelsus** [comment]
Im going to do the mergy mergy

**Comment by AlexandriteErikParacelsus** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by NuclearC** [comment]
guys will you add the new packet 0x30?

**Comment by Jhair2015** [comment]
@NuclearC You mean, official servers with MultiOgar? That's what I've been meaning.

**Comment by Tyler3D** [comment]
@NuclearC What's the packet's structure. I could give it a shot.

**Comment by Luka967** [comment]
@NuclearC I added the 0x30 packet but still no highlight.

**Comment by Tyler3D** [comment]
@Luka967 Does it show your current position?

**Comment by Luka967** [comment]
Nope not even that

**Comment by Agarian** [comment]
Take into consideration that the game now displays your position on the Leaderboard always, even if you're not # 10. MultiOgar isn't made for this, even though the client still tries to do this.

**Comment by NuclearC** [comment]
@Luka967 strange... because I tried to add that too and i got leaderboard highlight (but wrong position)

**Comment by Luka967** [comment]
I got it to work, displays exact position 👍

**Comment by cowpits** [comment]
nice @Luka967 can you tell me where to make the change?

**Comment by ItzLevvie** [comment]
^^ See https://github.com/Luka967/MultiOgar-Edited/tree/Updates

**Comment by cowpits** [comment]
ok cool thanks. i've noticed that on the latest 1.5.0 version players are freezing after a few minutes of play on agar.io client.

**Comment by Luka967** [comment]
I've played for 30+ minutes on two clients and none of them froze.

**Comment by cowpits** [comment]
i'm not freezing either but i run my servers on my hardware, people having the problem are on codeanywhere. I would think it's the container/host problem.

**Comment by cowpits** [comment]
sorry i'm confused as to which files got updated, is it like 7 of them?

**Comment by Luka967** [comment]
A lot of them xD

**Comment by cowpits** [comment]
lol, alright then i'll get the new download if they're all merged

**Comment by ItzLevvie** [comment]
@Luka967 

I have noticed that in Match Results, the 'food eaten' always says 0. This is because the client thinks that the food pellets are player cells

This is the reason why you can see its ('food pellets') mass while spectating.

**Comment by Agarian** [comment]
That must be why food cells have borders XD

**Comment by NuclearC** [comment]
@ItzLevvie so we need flag 0x80 for food cells :D

**Comment by Agarian** [comment]
Where we gonna add that? IDK packets xd

**Comment by NuclearC** [comment]
In UpdateNodes.js change this:
```Js
        var flags = 0;
        if (node.isSpiked)
            flags |= 0x01;      // isVirus
        if (node.cellType == 0)
            flags |= 0x02;      // isColorPresent (for players only)
        if (node.isAgitated)
            flags |= 0x10;      // isAgitated
        if (node.cellType == 3)
            flags |= 0x20;      // isEjected
        writer.writeUInt8(flags >>> 0);                  // Flags
        
        if (flags & 0x02) {
            var color = node.color;
            writer.writeUInt8(color.r >>> 0);       // Color R
            writer.writeUInt8(color.g >>> 0);       // Color G
            writer.writeUInt8(color.b >>> 0);       // Color B
        }
```
to:
```Js
        var flags = 0;
        if (node.isSpiked)
            flags |= 0x01;      // isVirus
        if (node.cellType == 0)
            flags |= 0x02;      // isColorPresent (for players only)
        if (node.isAgitated)
            flags |= 0x10;      // isAgitated
        if (node.cellType == 3)
            flags |= 0x20;      // isEjected
        if (node.cellType == 1)
            flags |= 0x80;
        writer.writeUInt8(flags >>> 0);                  // Flags

        if (flags & 0x80) writer.writeUInt8(0x01); // idk rlly what this do 

        if (flags & 0x02) {
            var color = node.color;
            writer.writeUInt8(color.r >>> 0);       // Color R
            writer.writeUInt8(color.g >>> 0);       // Color G
            writer.writeUInt8(color.b >>> 0);       // Color B
        }
```

**Comment by Agarian** [comment]
Oh wow

**Comment by Agarian** [comment]
I'm gonna PR that for you

**Pull request merged**
