### PR TITLE
Revert "More badwords variables"

### PR DESCRIPTION
**Pull request by MastaCoder**
Reverts Megabyte918/MultiOgar-Edited#1410

### CODE REVIEW

**Comment by MastaCoder** [comment]
Please review the comment on the commits for more information.

**Comment by GhostShot3** [comment]
Why you revert ?

**Comment by MastaCoder** [comment]
The gameserver makes everything lowercase and checks, no need for caps of the same words.

**Comment by GhostShot3** [comment]
Ok ,i uderstand.

**Pull request merged**
