### PR TITLE
PlayerID missing and more badwords

### PR DESCRIPTION
**Pull request by GhostShot3**

### CODE REVIEW

**Comment by GhostShot3** [comment]
Ops i commited in wrong branch :(

**Comment by GhostShot3** [comment]
Ready to merge.

**Comment by MastaCoder** [comment]
Conflicting!

**Comment by SomeoneCares11** [comment]
Not related Question: Is badwords forbidden from Chat & names, or just names?

Thanks

**Comment by GhostShot3** [comment]
Solved conflits ,now is ready to merge.

**Comment by MastaCoder** [comment]
@SomeoneCares11 Before when I used it I'm pretty sure it worked for names. Unsure if it still supports names, it should though if nobody changed it.

**Pull request merged**
