### PR TITLE
Issue template with rules

### PR DESCRIPTION
**Pull request by proxiemind**
I don't know, maybe this would help a little with issue traffic :cactus:

### CODE REVIEW

**Comment by AlexHGaming** [comment]
We have the wiki, so this is just another copy off of it.

**Comment by AlexHGaming** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/wiki/Issue-Template

**Comment by Tyler3D** [comment]
@AlexHGaming This issue template would show when you make a issue. But idk if it will work

**Comment by MastaCoder** [comment]
Let's test it out then xD

**Comment by proxiemind** [comment]
@AlexHGaming @Tyler3D Exactly my point, seems almost no one cares about template there, so now it's "enforced" a little.
@MastaCoder - will work for sure, something that makes workload on issues a little bit easier for you guys, I hope (done after seeing those wish lists and other spamy "issues" on mail :hourglass_flowing_sand: )

**Pull request merged**
