### PR TITLE
Add srcFiles variable

### PR DESCRIPTION
**Pull request by MastaCoder**
This is for those that want to run multiple gameserver.ini's under 1 game. (Like myself) Allows people to change 1 variable to change the directory to all dependencies that are loaded.

NOTE: We can try to move this to gameserver.ini if people request it, but I find it to do pretty much the exact same thing this does. It does offer some more options though if it's in the gameserver.ini.

### CODE REVIEW

**Comment by Megabyte918** [comment]
Why would you want to run two gameserver.ini's at once?

**Comment by MastaCoder** [comment]
For people that have multiple gamemodes. Run each of them under different ports, but the same source files.

**Comment by Megabyte918** [comment]
Alright sounds good, Thanks @MastaCoder :)

**Comment by MastaCoder** [comment]
I thought I'd just push this because I usually run my files under different directories and different names. :)

**Pull request merged**
