### PR TITLE
Improve kickbot

### PR DESCRIPTION
**Pull request by Agarian**
- Change `kickbot` command to `kickbots`
- Remove an overrided message
- Slightly simpler `no removed bots` variable

### CODE REVIEW

**Comment by Tyler3D** [comment]
@Agarian Can't you add the || symbol somewhere in the code to have both kickbot and kickbots?

**Comment by Agarian** [comment]
Actually, i didn't consider that, i'll close this for now

**Comment by Agarian** [comment]
But, at the same time, i could add it in the command shortcuts area, but no. I'll just leave kickbot where it is

**Comment by Tyler3D** [comment]
ok

**Pull request closed without merging**
