### PR TITLE
Added split velocity 

### PR DESCRIPTION
**Pull request by FantasyIsBae**
Idk if this can be usefull , but i tested it and it works fine :) @Megabyte918

### CODE REVIEW

**Comment by Megabyte918** [comment]
@FantasyIsBae I don't think we need this.. I mean if people want to change the distance they can just do it through GameServer, I can't think of a time where I would need to change it in game through the config whereas you can do the same thing through GameServer. Also having the server call back to gameserver.ini every time a player cells splits could potentially decrease performance, especially if the person is hosting a big server with tons of players constantly splitting.

**Comment by FantasyIsBae** [comment]
Yep , can't argue with that :)

**Comment by Megabyte918** [comment]
@FantasyIsBae Sorry haha, I would have done the same thing if the performance wasn't so sensitive >.<

**Comment by FantasyIsBae** [comment]
I mean there's room for improvement xD

**Comment by Megabyte918** [comment]
Yes definitely

**Pull request closed without merging**
