### PR TITLE
Support for Protocol 13's Leaderboard

### PR DESCRIPTION
**Pull request by Tyler3D**
This closes https://github.com/Megabyte918/MultiOgar-Edited/issues/704, and closes https://github.com/Megabyte918/MultiOgar-Edited/issues/703

I wonder if Github will auto-close these issues when this is merged xD                                                       
             ->https://help.github.com/articles/closing-issues-via-commit-messages/

### CODE REVIEW

**Comment by Tyler3D** [comment]
Thanks to @NuclearC for decoding the protocol

**Comment by Agarian** [comment]
Kudos, it actually works! @Megabyte918 Merge this

**Comment by NuclearC** [comment]
you can remove protocol v11, its not used anymore by any client

**Comment by ZfsrGhS953** [comment]
@Tyler3D It's best to remove protocol 11, it existed for a very short time frame that obviously wasn't enough for anyone to make a client for it. And even if someone did make a client for it... Just remove it anyway, we don't endorse clients that aren't made by Moneyclip.

**Comment by NuclearC** [comment]
@Tyler3D i made client since protocol v9 :D

**Comment by MastaCoder** [comment]
Guessing there is still some work to do, holding back before merging. Let me know once you're done.

**Comment by Tyler3D** [comment]
@MastaCoder No, I'm done. I just wanted to remove protocol 11 and add the friend list thingy

**Comment by MastaCoder** [comment]
🎉

**Pull request merged**
