### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by Luka967** [comment]
I get errors in agar when I added the 0x80 flag.

**Comment by ItzLevvie** [comment]
Not for me

image

**Comment by ItzLevvie** [comment]
You probably added

```js
if (node.cellType == 1) flags |= 0x80;
```

but that will cause your agar to go to a blank white screen

**Comment by Megabyte918** [comment]
.

**Comment by Luka967** [comment]
Ohhhh
so there's an additional byte if it's a pellet
Didn't add that, thanks for reminding me

**Comment by Megabyte918** [comment]
Thanks @NuclearC and @ItzLevvie, I appreciate it :)

**Comment by ItzLevvie** [comment]
@Megabyte918 Luka has it fixed on his repo

**Pull request merged**
