### PR TITLE
Added config for console-plus.js

### PR DESCRIPTION
**Pull request by SuperOP535**
This will allow users to easily change username, password and port of the web console in a basic JSON file

### CODE REVIEW

**Comment by DeadLord1337** [comment]
Nice

**Comment by Megabyte918** [comment]
@SuperOP535 Good idea! However I don't see the need for the .json file when there is only 3 configs required. 

I'll figure out a way to grab those configs from ```gameserver.ini```, later.

**Comment by SuperOP535** [comment]
Okay, I asked about gameserver.ini but someone said it is not related to the game so I made a JSON instead

**Comment by Agarian** [comment]
[It is related to the game...](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/gameserver.ini#L1)

**Pull request merged**
