### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by Agarian** [comment]
That allows connection, but not spawning. @ItzLevvie

**Comment by ItzLevvie** [comment]
^^ Works for spawning too.

**Comment by Agarian** [comment]
I thought something was wrong with the LB, when i noticed "An unnamed cell" doesn't appear on it.

**Comment by NiesamoWhite** [comment]
i can't spawn

**Comment by AlexHGaming** [comment]
can't press 'play'
it connects me but can't join the server -_-

**Comment by Agarian** [comment]
Probably the custom skins script @AlexHGaming

**Comment by AlexHGaming** [comment]
works now.
BTW profile picture buddies for a long time lmfao

**Comment by Gigabyte918** [comment]
@Agarian and @AlexHGaming i am confused in Who is saying that! Confused in same profile hahaha

**Pull request merged**
