### PR TITLE
"Beautify" other JS files

### PR DESCRIPTION
**Pull request by Agarian**
Title says it all (making the JS files more readable, and just better looking).

- GameServer: finished
- PacketHandler: finished
- PlayerTracker: finished
- Index.js: finished
- HttpsServer: finished
- AI (bot/minion) files: finished
- Entity Files: finished
- Gamemode Files: finished
- Modules Files: finished
- Packet Files: finished
- Scripts Files: finished

If I happened to miss any files (besides other Index files), let me know! Otherwise, this is ready to merge.

### CODE REVIEW

**Comment by AlexHGaming** [comment]
fuckin hell how many files

**Comment by Agarian** [comment]
A lot, but I've realized this kind of goes against Barbosik's formatting rules. Closing now

**Comment by Luka967** [comment]
lol

**Comment by MastaCoder** [comment]
I don't like beautifying scripts. Sometimes they squish code that looks better not squished together :)

**Pull request closed without merging**
