### PR TITLE
Performance

### PR DESCRIPTION
**Pull request by DeadLord1337**

### CODE REVIEW

**Comment by Luka967** [comment]
Literally nothing's been changed here.

**Comment by DeadLord1337** [comment]
:0

**Comment by AlexHGaming** [comment]
rekt

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 That will make minions only collect pellets within a radius of 
```javascript
31622.776601683792
```
. It still covers the 
```javascript
13466.666666666668 * 7866.666666666667
```
viewbox rectangle at the default serverMinScale, so your change won't do anything.

**Comment by AlexHGaming** [comment]
What?

**Comment by ZfsrGhS953** [comment]
@AlexHGaming His change will only have effect on very large minion viewboxes.

**Comment by Agarian** [comment]
He's done it again here: #1379

**Comment by AlexHGaming** [comment]
Ah.

**Pull request closed without merging**
