### PR TITLE
Fixed version to 1.6.1

### PR DESCRIPTION
**Pull request by ArixProject**

### CODE REVIEW

**Comment by Fan7asy** [comment]
We're in 1.6.1...

**Comment by Fan7asy** [comment]
@ArixProject

**Comment by ArixProject** [comment]
@Fan7asy fixed

**Comment by Fan7asy** [comment]
What the hell is this for?

**Comment by ArixProject** [comment]
idk

**Comment by ArixProject** [comment]
okay i close

**Comment by AlexHGaming** [comment]
@ArixProject this doesn't mean the current version of the repo, it means the benchmarks of 1.6.0.

**Comment by ArixProject** [comment]
@AlexHGaming close?

**Comment by AlexHGaming** [comment]
@ArixProject i would say so.

**Pull request closed without merging**
