### PR TITLE
Updated Version of the Restart Time

### PR DESCRIPTION
**Pull request by MastaCoder**
This is a better way to run the restartTime than add another tick counter. (Since you can also move it to another tick counter so that it doesn't run every single second)

~~Don't accept this yet, I found a much more efficient way of doing it.~~ Nevermind the other method didn't work.

### CODE REVIEW

**Comment by MastaCoder** [comment]
I'll redo this.

**Comment by Gimmo** [comment]
This shoul be removed completely. Someone should find the reason(root) of server problems.

**Comment by MastaCoder** [comment]
what problem?

**Comment by Gimmo** [comment]
Increasing lag at a time under load. Server not stable. This is a problem.

**Pull request closed without merging**
