### PR TITLE
Issue Template shows when you make a issue

### PR DESCRIPTION
**Pull request by Tyler3D**

### CODE REVIEW

**Comment by Tyler3D** [comment]
Unfortunately, only Collaborators can edit this

**Comment by Megabyte918** [comment]
I wanted to add something like this a while ago, but I decided not to because nobody would follow it just like no one bothers to look at the issue template on the wiki before making an issue. The same thing happened with Ogar Unlimited with the issue template, people just ignored it and made the issue anyway.

**Comment by Tyler3D** [comment]
@Megabyte918 Your right. But at least, people are reminded of the issue template before they make a issue.

**Comment by MastaCoder** [comment]
But there is a wiki. What's the point on adding an extra file to the project when people never even look at it, it's just going to be there to be deleted.

**Comment by Tyler3D** [comment]
@MastaCoder This is a github feature. When ever you make a issue when this file exists, github displays this  template

**Comment by MastaCoder** [comment]
Really? Never seen it before or it's too small to even notice lol.

**Comment by Tyler3D** [comment]
xD

**Comment by MastaCoder** [comment]
lmao :3

**Pull request closed without merging**
