### PR TITLE
supports server restart at specific time.

### PR DESCRIPTION
**Pull request by FirstCodeReviewer**
Its slightly modified to remove some unnessary loops but the Idea is the same.
Thanks to bbcnkl (https://github.com/bbcnkl)

### CODE REVIEW

**Comment by FirstCodeReviewer** [comment]
Updated the PR. Dear Collaborators please read again. :)
i would also like to say Thank you to Tombez.

**Comment by Tombez** [comment]
I started a PR on FirstCodeReviewers fork, so don't merge until he merges that one.

**Comment by Tombez** [comment]
He merged it, all good to go. :)

**Comment by FirstCodeReviewer** [comment]
Its squashed to one commit to not pollute the commit history.

**Comment by TopoR1** [comment]
Good work bro👍

**Comment by B0RYS** [comment]
@Agarian can you fix the conflicts please

**Pull request closed without merging**
