### PR TITLE
Added Auto-Restart

### PR DESCRIPTION
**Pull request by Tyler3D**
Default is 60 minutes.

### CODE REVIEW

**Comment by MastaCoder** [comment]
Creating another interval could surely cause some lag, no?

**Comment by Tyler3D** [comment]
In the batch or the js?

**Comment by Tyler3D** [comment]
If you are talking about the batch then no, because the goto start line isn't ran until the node index.js line finshes

**Comment by MastaCoder** [comment]
https://github.com/Megabyte918/MultiOgar-Edited/pull/148/commits/a1b725f59a87222ad701141771238bbfcac5b504#diff-ee5616beb8aa0f352a3f697cf7c1d331R174

**Comment by Tyler3D** [comment]
I don't know how to test for lag but, since it is only one calculation and only happens on start it shouldn't affect performance much.

**Comment by MastaCoder** [comment]
No it's not just a calculation. It's a tick added to be running until the program is done. (At least I'm pretty sure it works like that.)

You're pretty much adding another timer that would continue to run until the program is done. There is an easier way to do this, I'll add it tonight. (If I have time)

**Comment by Tyler3D** [comment]
So, SetInterval?

**Comment by Tyler3D** [comment]
Well idk if this is the best method.

**Comment by MastaCoder** [comment]
I'll update it on my git, give me a bit.

**Comment by Tyler3D** [comment]
Ok

**Comment by CalvinDKL** [comment]
YESS, IT WILL BE ADDED!!!! Thanks tyler! And Masta for accepting it!

**Comment by MastaCoder** [comment]
#149

**Comment by Megabyte918** [comment]
@Tyler3D @MastaCoder The exit command is broken on both forks, when you use the exit command it restarts the server rather than exiting the program.

**Comment by Tyler3D** [comment]
Crap

**Comment by Tyler3D** [comment]
I can't fix it now. I'm not on my pc

**Comment by Tyler3D** [comment]
I forgot about that

**Comment by MastaCoder** [comment]
@Megabyte918 Can't someone just do ctrl + c to exit the program? It works for both Linux and Windows.

**Comment by Megabyte918** [comment]
@MastaCoder Yes but is defeats the  purpose of having an "exit" command, and some people do not know that they can use ctrl + c

**Comment by MastaCoder** [comment]
Okay. @Megabyte918

**Comment by Tyler3D** [comment]
@Megabyte918 What about the big 'X' button in the top right for exiting on Windows.
For mac, the red button on the top left. And for linux, well there's always a bat.

**Comment by MastaCoder** [comment]
Some people run it through the terminal, cmd, or ssh itself. You can't just x those if you have commands in use already. (You can't x ssh at all..)

**Pull request closed without merging**
