### PR TITLE
Add Auto-Restart, fix typo

### PR DESCRIPTION
**Pull request by AlexHGaming**
Firstly, thanks to @cowpits for getting the auto-restart code.
Secondly, how did no one notice this typo that crashes the server? Well, I fixed it anyways.
Any more typos you see please let me know below!

### CODE REVIEW

**Comment by ZfsrGhS953** [comment]
@AlexHGaming setTimeout :smile: :smile: :smile: :smile: What the hell, more like "Add lag" :smile:
Better code:
In loadConfig:
```javascript
this.config.serverRestart = this.config.serverRestart === 0 ? 1e999 : this.config.serverRestart * 1500;
```
And the setTimeout line (why the hell have you put it in the if with the server stats):
```javascript
if (this.tickCounter > this.config.serverRestart) process.exit(1);
```
And the crashes were happening because no one listened to [me](https://github.com/Megabyte918/MultiOgar-Edited/pull/1221)

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 its @cowpits' code, mehhhhhhh

**Comment by AlexHGaming** [comment]
@Fan7asy Please can you merge this?

**Comment by cowpits** [comment]
I did this for my servers, I wasn't expecting to put it here. If there's a better way please go ahead.

**Comment by ZfsrGhS953** [comment]
@AlexHGaming @Fan7asy I think @Megabyte918 will un-merge or use my version instead, because he doesn't like laggy code like this one.

**Pull request merged**
