### PR TITLE
Mini clean-up. Fix ANOTHER typo

### PR DESCRIPTION
**Pull request by AlexHGaming**
@Megabyte918 fix ur fukin spellin 😂

### CODE REVIEW

**Comment by pabloalber84** [comment]
:v

**Comment by FantasyIsBae** [comment]
"dependencies" is the correct spelling Alex.

**Comment by Luka967** [comment]
v

**Comment by Wair1o17** [comment]
lol

**Comment by Agarian** [comment]
k

**Comment by AlexHGaming** [comment]
k

**Pull request merged**
