### PR TITLE
Revert "Added the lord and savior pickle"

### PR DESCRIPTION
**Pull request by AlexandriteErikParacelsus**
Reverts Megabyte918/MultiOgar-Edited#306

### CODE REVIEW

**Comment by MastaCoder** [comment]
What's up with all these spam and useless commits..?

**Comment by Megabyte918** [comment]
I don't know.

**Comment by MastaCoder** [comment]
Can you revert everything before 2b74ce5624984a1d23d10a873460faaa24b95d09 and delete all these commits? It's just annoying how there are like so many random and useless commits at the top 😄  @Megabyte918

**Comment by Megabyte918** [comment]
I would but doing so would only make more commits @MastaCoder

**Comment by MastaCoder** [comment]
@Megabyte918 You can delete commits xD

http://stackoverflow.com/questions/448919/how-can-i-remove-a-commit-on-github

**Comment by Megabyte918** [comment]
Oh god I have to use git.. last time I tried to use git It drove me insane and I quit because of frustration lol
I'm barely know how to use git, every time I fail a command a little part of me dies inside
Also why do you want collaborator? lol

**Pull request closed without merging**
