### PR TITLE
Small console UI tweaks and Readme :)

### PR DESCRIPTION
**Pull request by FantasyIsBae**

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Why aren't you collaborator anymore @FantasyIsBae ? Did you remove your own role or did you get removed the role ??

**Comment by FantasyIsBae** [comment]
@Megabyte918 Thought i was done with MultiOgar-Edited so he removed me , I don't blame him lol

**Comment by Luka967** [comment]
lol

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by AlexHGaming** [comment]
@Megabyte918 I have added an extra section to the Wiki:  'clients' <- Be sure to check it out if you like it
Seems loads of people are liking it, I was bored and made it for everyone, I started all this off lol.
If you want help with anything else just let me know 👍

**Comment by AlexHGaming** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
@AlexHGaming Thanks
@FantasyIsBae Is this ready for merge?

**Comment by AlexHGaming** [comment]
You should give him collaborator back, 1 isn't enoguh

**Comment by Megabyte918** [comment]
I sent him an invite like 3 days ago, he just hasn't accepted it yet

**Comment by FantasyIsBae** [comment]
Yes its ready to merge , I'll keep adding stuff on as time progresses :)

**Comment by FantasyIsBae** [comment]
@Megabyte918 Pls resend the invite thanks :)

**Comment by AlexHGaming** [comment]
@Megabyte918 I wonder how long it'll take me to earn it, time to show some trustworthy

**Comment by FantasyIsBae** [comment]
@AlexHGaming I find you quite trustworthy , but its @Megabyte918 's choice lel

**Comment by Tyler3D** [comment]
It's cause of the GitHub system. He has to give you write access to give issue stuff.

**Comment by AlexHGaming** [comment]
@FantasyIsBae Ya see, I did do some errors in the past, he can do what he wants, he hasn't really seen much of my solutions to other people's issues, but he's seen some lol. I even made a full [Wiki](https://github.com/Megabyte918/MultiOgar-Edited/wiki) page adding 'clients' alongside the actual base. And yeah it's his choice lol, doesn't really matter. BTW now it's saying agar.io is protocol '8' instead of '11', you need to fix that @Megabyte918

**Comment by Tyler3D** [comment]
Actually this pull request changed the 11 back to a 8 and ws needs to be reverted to 1.1.0. ANND the 1.6.0 on the rereadme was changed to a 1..5.0

**Comment by Megabyte918** [comment]
I'm going to add a few things back to the readme, if you don't mind.

**Comment by AlexHGaming** [comment]
k

**Comment by Luka967** [comment]
don't k him xD

**Comment by AlexHGaming** [comment]
k.

**Comment by Luka967** [comment]
k den

**Comment by MastaCoder** [comment]
kk

**Comment by Luka967** [comment]
ned k
xD

**Comment by MastaCoder** [comment]
KEK

**Comment by AlexandriteErikParacelsus** [comment]
kock

**Comment by FantasyIsBae** [comment]
@Megabyte918 I don't mind m8

**Comment by Luka967** [comment]
KOCK XDDDDD

**Pull request merged**
