### PR TITLE
Not comment!! :D

### PR DESCRIPTION
**Pull request by DeadLord1337**

### CODE REVIEW

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 Needs modifications of GameServer.js (to correctly handle entries with spaces.

**Comment by AlexHGaming** [comment]
>Not comment!! :D

Sorry I commented.

**Comment by ZfsrGhS953** [comment]
@MastaCoder @Megabyte918 Obsoleted by #1393 .

**Comment by ZfsrGhS953** [comment]
@AlexHGaming He probably meant to say that this isn't an issue created in the pull request section.

**Pull request closed without merging**
