### PR TITLE
Enhancement

### PR DESCRIPTION
**Pull request by Agarian**
Make it to where this config doesn't have to be a decimal for a percentage.

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Good one, less confusion.

**Comment by Tyler3D** [comment]
I think you wanna divide instead of multiply @Agarian

**Comment by Luka967** [comment]
^^ @Agarian

**Comment by Agarian** [comment]
No, actually

**Comment by Luka967** [comment]
*If I divide 50 with 100, it would be 0.5.
`Math.random()` gives 0-1.

**Comment by AlexHGaming** [comment]
Am I in a maths lesson?

**Comment by Luka967** [comment]
No it's a simple brain conclusion.
```js
Math.random() <= (50 * 100)
= /* number from 0 to 1 */ <= 5000 // always true

Math.random() <= (50 / 100)
= /* number from 0 to 1 */ <= 0.5 // 50% true 50% false
```

**Pull request closed without merging**
