### PR TITLE
Adds calculator for spawn mass configuration

### PR DESCRIPTION
**Pull request by AlexHGaming**

### CODE REVIEW

**Comment by AlexHGaming** [comment]
accidentally removed the maxcells bit on the first commit, so i readded it on the 2nd one.

**Comment by MastaCoder** [comment]
Wtf, why do they need a website to calculate a simple formula? If they can't use a calculator they shouldn't be using MultiOgar lmfao.

**Comment by FantasyIsBae** [comment]
XD

**Comment by AlexHGaming** [comment]
@MastaCoder idk. some people just dk how to calculate the right thing. i get questions on how to do this and that whatever

**Comment by MastaCoder** [comment]
If they don't know how to calculate why are they using MultiOgar >:( It's explicitly stated in the code how to do it..

**Pull request merged**
