### PR TITLE
Improved pop split

### PR DESCRIPTION
**Pull request by DeadLord1337**

### CODE REVIEW

**Comment by Agarian** [comment]
This changed code has the same effect as the original code...

**Comment by ZfsrGhS953** [comment]
@Agarian Math.pow gives slightly different results.

**Comment by DeadLord1337** [comment]
@Agarian I noticed a difference in pop split :/

**Comment by Megabyte918** [comment]
It "kind of" makes a difference when you plug numbers in:
```js
780 * pow(10000, 0.0124) = 874.3687
780 * pow(10000, 0.0122) = 872.7595359

780 * pow(15000, 0.0124) = 878.7758923
780 * pow(15000, 0.0122) = 877.0874888
```
But honestly, I don't see the point of merging if all you are changing is that value by .0002.

**Pull request closed without merging**
