### PR TITLE
Ogartracker

### PR DESCRIPTION
**Pull request by SuperOP535**
New tracker added, cleaned up the code a bit

### CODE REVIEW

**Comment by B0RYS** [comment]
Why increment the version?

**Comment by B0RYS** [comment]
The package version of npm doesn't need to be changed, it won't end up incompatible.

**Comment by SuperOP535** [comment]
Megabyte said I should do it

**Comment by SuperOP535** [comment]
And it was not a major version update, only a simple patch

**Comment by B0RYS** [comment]
Therefore you shouldn't increment the version.

**Comment by Luka967** [comment]
If you were to follow semver, this update would constitute for a minor version. It'd make all sense to increment it anyway, as versions were made for simpler feature tracking and better software support, so why not increment it?

**Comment by SuperOP535** [comment]
It's been on the same version for a year now (package 1.6.2, source 1.6.1 reeee inconsistency) so it's probably time to change that imho (this pr fixes any future inconsistencies too)

**Comment by B0RYS** [comment]
Unless its a major update, there is no reason to increment the version.

**Comment by SuperOP535** [comment]
It was not a major version increment

**Comment by B0RYS** [comment]
I didn't say it was.

**Comment by SuperOP535** [comment]
Thankn't you sir

**Pull request closed without merging**
