### PR TITLE
Fix server not working when using uws module (for Updates branch)

### PR DESCRIPTION
**Pull request by Luka967**
I've just noticed that uws gives ArrayBuffers on messages - this change should replace the message with a Buffer that shares memory with the old ArrayBuffer.
Should fix server not working with uws, I've not tested it; if not I'll investigate more.

### CODE REVIEW

**Comment by AlexHGaming** [comment]
k

**Comment by Megabyte918** [comment]
Does this work with the UWS module? I need to know before I can merge

**Comment by Luka967** [comment]
It doesn't, gotta debug it more.

**Comment by Luka967** [comment]
Made it work now but had to move the `sendPacket` function to the PacketHandler due to errors with the old technique. Committing changes now

**Comment by Luka967** [comment]
done, tested with both ws and uws and seems to be working

**Comment by Megabyte918** [comment]
It does not work (atleast for me.)
I think it'd be best to keep it in GameServer, to avoid errors. Why was it moved to PacketHandler in the first place?

**Comment by Luka967** [comment]
I've broken bots xD

**Comment by Luka967** [comment]
It works now.

> I think it'd be best to keep it in GameServer, to avoid errors.

It was kept as a custom function in the `ws` module. It wasn't even added when you switch to `uws` before these updates. Barbosik compromised this by moving that function over to `GameServer.start`.
I forgot that bots don't have `socket.send`, and tries emitting the close event on `FakeSocket` (and of course failing).

> Why was it moved to PacketHandler in the first place?

The `.sendPacket` function is there just for checking the websocket state (i.e. if the connection is closed) before actually sending a packet. It feels more suitable for `PacketHandler` than for `GameServer`. I also have it set up that way on my multiverse server and does the job fine.

**Comment by Megabyte918** [comment]
@Luka967 It seems it is having trouble emitting "close". [Take a look](http://i.imgur.com/qTncX2X.png)
I've tried replacing "socket" with various other things for emitting close but nothing seems to be working for it. Do you know why this might be?

**Comment by Luka967** [comment]
Sure, I forgot about minions too lol

**Comment by Megabyte918** [comment]
@Luka967 Thank you xd

**Comment by Jhair2015** [comment]
fix red color LB :)

**Comment by Agarian** [comment]
@Jhair2015 megabyte just did in the #446

**Pull request merged**
