### PR TITLE
A quick add

### PR DESCRIPTION
**Pull request by AlexHGaming**

### CODE REVIEW

**Comment by pabloalber84** [comment]
:v 
"Big fixes"
The first not are needed, because the reference are to Barbosik, not for the project of he.

**Comment by AlexHGaming** [comment]
@pabloalber84 It's worth pointing it out.

**Comment by pabloalber84** [comment]
Why not, the 

> on this [project]
Can be

> on [this project]

**Comment by AlexHGaming** [comment]
Doesn't really matter.

**Pull request closed without merging**
