### PR TITLE
Skin fixes (at least for cigar client)

### PR DESCRIPTION
**Pull request by Niall7459**
This fixes the skins for Cigar clients.
This works for me on Cigar client.

But I wouldn't be sure about agar.io skins

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Wait wait wait, only agar.io had been affected, cigar was never affected lol

**Comment by Niall7459** [comment]
Latest version of MultiOgar Edited does not work with skins on Cigar

**Comment by Agarian** [comment]
Then that's Cigar's issue, not ours. Because skins seem to work fine on my cigar client (and it uses the latest code).

**Comment by AlexHGaming** [comment]
Same for me.

**Comment by Agarian** [comment]
I'd assume that this skins for clients that support premium skins...

**Comment by Niall7459** [comment]
Ah alright then no need to merge then I guess.
It just fixes <skin> skins

**Comment by MastaCoder** [comment]
That % inner file, the client is supposed to add it itself isn't it? You most likely have an edited version.

**Comment by Agarian** [comment]
*MultiOgar-Edited-Edited*

**Pull request closed without merging**
