### PR TITLE
bored - did this

### PR DESCRIPTION
**Pull request by AlexHGaming**
Little does help :)

### CODE REVIEW

**Comment by FantasyIsBae** [comment]
Replace "**swear / racist words**" with "**profanity**"
Its a bit more professional @AlexHGaming

**Comment by AlexHGaming** [comment]
@FantasyIsBae Alright

**Comment by AlexHGaming** [comment]
**profanity**

**Comment by AlexHGaming** [comment]
@FantasyIsBae

**Comment by AlexHGaming** [comment]
_Incoming megabyte_

**Comment by AlexHGaming** [comment]
lmfao perfect time

**Comment by FantasyIsBae** [comment]
xdd

**Comment by AlexHGaming** [comment]
Haha come discord

**Pull request merged**
