### PR TITLE
New Discord server

### PR DESCRIPTION
**Pull request by SuperOP535**
yes

### CODE REVIEW

**Comment by SuperOP535** [comment]
evil makan ignored my pull and commited by his own >:(

**Comment by MastaCoder** [comment]
Thought I'd add it in a smaller button type under the title so it's not so intrusive. e44a8e7ff1b604588d7de92808bee0af40bec445

**Comment by MastaCoder** [comment]
Damn b you is fast

**Comment by SuperOP535** [comment]
yes

**Pull request closed without merging**
