### PR TITLE
Added Slither Mode

### PR DESCRIPTION
**Pull request by Tyler3D**

### CODE REVIEW

**Comment by Tyler3D** [comment]
Slitherin around

**Comment by Tyler3D** [comment]
xD

**Comment by Tyler3D** [comment]
Some day I will add slithering bots tooo

**Comment by Megabyte918** [comment]
This looks like a ton of performance issues to me :/

**Comment by Tyler3D** [comment]
This increases lag by only ~4-5 ms on my pc with 1000 bots

**Comment by Tyler3D** [comment]
But, if you say so

**Comment by Megabyte918** [comment]
@Tyler3D 4-5ms is a very significant amount. You can see the different lag messages that are displayed through [this function.](https://github.com/Megabyte918/MultiOgar-Edited/blob/master/src/modules/ini.js#L217)
This fork of multiogar is a few ms faster than the original, which is also significant given the amount that takes it to start lagging. So merging this would set it back a long way in terms of performance. I might actually convert this into a gamemode myself if I have the time that way performance is not affected.

**Comment by Tyler3D** [comment]
@Megabyte918 Damm I didn't think 5ms was a lot

**Pull request closed without merging**
