### PR TITLE
Reduce Lag

### PR DESCRIPTION
**Pull request by Tyler3D**
Reduces Lag by getting rid of unnecessary functions. Cause gamemode command was removed.

### CODE REVIEW

**Comment by AlexandriteErikParacelsus** [comment]
May I merge??

**Comment by AlexandriteErikParacelsus** [comment]
@Tyler3D

**Comment by Tyler3D** [comment]
@AlexandriteErikParacelsus Let me Test XD

**Comment by Tyler3D** [comment]
I forgot

**Comment by AlexandriteErikParacelsus** [comment]
Ok lel

**Comment by Tyler3D** [comment]
@AlexandriteErikParacelsus Ok ready for merge

**Comment by AlexandriteErikParacelsus** [comment]
sorry for late respond @Tyler3D

**Comment by Tyler3D** [comment]
@AlexandriteErikParacelsus  np

**Pull request merged**
