### PR TITLE
Last Man Standing Gamemode

### PR DESCRIPTION
**Pull request by Tyler3D**
Not Ready For Merge Yet. Need to Find Syntax Error. I spend An Hour looking for the freakin' semicolon. Couldn't find it. Anyway the logic is done, You die you can't spawn. You can only spectate like Hunger Games. I couldn't figure out how to Reset the thing. So, once LMS starts you can't spawn again until you restart the server.

### CODE REVIEW

**Comment by Tyler3D** [comment]
@Megabyte918 Why is this wrong?
``var LMSStarting = function () {

    StartofLMS = true;
    Logger.info("LMS HAS STARTED");
};

**Comment by Megabyte918** [comment]
What's the error

**Comment by Megabyte918** [comment]
the StartofLMS variable is outside the global scope @Tyler3D

**Comment by Tyler3D** [comment]
The error is:
SyntaxError: Unexpected token var

**Comment by Tyler3D** [comment]
And the StartofLMS variable in declared in the very first lines of code

**Comment by Tyler3D** [comment]
So it's global

**Comment by Megabyte918** [comment]
@Tyler3D make it a prototype instead

**Comment by Tyler3D** [comment]
Ok

**Comment by Tyler3D** [comment]
Nope Didn't work
LMS.prototype.LMSStarting = function () {
^^^
SyntaxError: Unexpected identifier

**Comment by Megabyte918** [comment]
where did you put it?

**Comment by Tyler3D** [comment]
Same Place

`
LMS.prototype.LMSStarting = function () {
    StartofLMS = true;
    Logger.info("LMS HAS STARTED");
};
`

**Comment by Tyler3D** [comment]
I just replaced the var with LMS.prototype

**Comment by Megabyte918** [comment]
@Tyler3D do you have skype/discord or something that we could talk on rather than here? it would be alot easier

**Comment by Tyler3D** [comment]
I got A Discord

**Comment by Tyler3D** [comment]
And yea

**Comment by Tyler3D** [comment]
Send me a link

**Comment by Megabyte918** [comment]
@Tyler3D just send me a freind req 
#2990

**Comment by Tyler3D** [comment]
Didn't Work

**Comment by Megabyte918** [comment]
@Tyler3D https://discord.gg/Rj5KJ

**Comment by Tyler3D** [comment]
Done

**Comment by Tyler3D** [comment]
@Megabyte918 Are you online?

**Comment by Tyler3D** [comment]
Ready for Merge

**Comment by Tyler3D** [comment]
@Megabyte918

**Comment by Megabyte918** [comment]
Thanks @Tyler3D, this is pretty cool!

**Comment by Tyler3D** [comment]
@Megabyte918 Thanks

**Comment by Tyler3D** [comment]
@Megabyte918 Can you give me Credit xD

**Comment by Tyler3D** [comment]
@Megabyte918 And you should put the new gamemode in the readme

**Comment by Tyler3D** [comment]
@Megabyte918 Can you give me Contribute Powers.
Like Writing to Files

**Pull request closed without merging**
