### PR TITLE
Error gameserver.js

### PR DESCRIPTION
**Pull request by ChikoxD**
**Lucas967** I get the following error attached an error image
[https://i.imgur.com/0kJ8wsb.png](https://i.imgur.com/0kJ8wsb.png)

### CODE REVIEW

**Comment by AlexHGaming** [comment]
@ChikoxD link is invalid.

**Comment by AlexHGaming** [comment]
@ChikoxD oh wait nvm, this doesn't happen on the current version. Reinstall your server then try again.

**Comment by Fan7asy** [comment]
Why is this a Pull Request?

**Comment by Fan7asy** [comment]
You're on a completely different branch.

**Comment by Agarian** [comment]
Dude what even?

**Pull request closed without merging**
