### PR TITLE
Update Virus Physics v2

### PR DESCRIPTION
**Pull request by AlexHGaming**
Is this better @Fan7asy ?

### CODE REVIEW

**Comment by Luka967** [comment]
No

**Comment by Agarian** [comment]
I don't see what's so bad about it, @Luka967.

**Comment by AlexHGaming** [comment]
probs jokin lol

**Comment by ZfsrGhS953** [comment]
@Luka967 Perhaps you should add ", in terms of execution time".

**Comment by Fan7asy** [comment]
Cl0sed

**Comment by AlexHGaming** [comment]
Haven't tested the new Luka physics, I was gonna close this after Luka's was merged @Fan7asy

**Comment by ZfsrGhS953** [comment]
@Fan7asy Check your messages before sending...

**Comment by Luka967** [comment]
Bet t|-|at w4s 1ntenti0naL

**Comment by Agarian** [comment]
k

**Comment by ZfsrGhS953** [comment]
@Luka967 Look where the O and 0 keys are.

**Comment by Fan7asy** [comment]
Ye4h l00k where the O 4nd 0 k3y5 @r3.

**Comment by Agarian** [comment]
kd3n

**Pull request closed without merging**
