### PR TITLE
MultiOgar Binary!

### PR DESCRIPTION
**Pull request by Tyler3D**

### CODE REVIEW

**Comment by AlexandriteErikParacelsus** [comment]
noice

**Comment by AlexandriteErikParacelsus** [comment]
Tell me when you're done, I can merge it for you

**Comment by Tyler3D** [comment]
@AlexandriteErikParacelsus I finished when I opened the pull request XD

**Comment by Megabyte918** [comment]
@Tyler3D What's in the file? Is it just src compressed into an exe?

**Comment by Tyler3D** [comment]
@Megabyte918 And the modules

**Comment by Tyler3D** [comment]
@Megabyte918 I tested it. It works

**Comment by Megabyte918** [comment]
@Tyler3D This is a good idea and its convenient and all... but theres a lot of problems with it.

1.) You can't edit configs, since gameserver.ini is located within the exe

2.) It will have to stay constantly updated, since theres so many commits and updates all the time, I will have to download and re-compress the newest version into an exe, or else whoever decides to run it with the exe will be using an outdated version.

3.) It takes away from the point of having a repo. Why have a repo when you can just compress the whole thing to an exe? Then it becomes less open-source, people can't edit files as they please, and theres basically no point in going to the repo in the first place if you can just download and run the exe.

4.) People who make tutorials and other videos such as those on how to make private servers can just download and distribute the exe file to their viewers, rather than link the repo. People won't know this repo exists if theres an exe going around, this could also lead to some malicious software being distributed.

**Pull request closed without merging**
