### PR TITLE
Update Virus Physics

### PR DESCRIPTION
**Pull request by AlexHGaming**
Why did we have this line originally? You're basically adding numbers around until there is a total. Just add 1 number damnit! Also tested out, it's quite good for popsplitting and not so bad from the vanilla :D

### CODE REVIEW

**Comment by Agarian** [comment]
I can't help but think that the number should be 3.885, not 4. And I'm pretty sure that `(4.55 - 4.55)` cancels its self out. I mean, `(4.55 - 4.55) + 3.885` pretty much says `0 + 3.885`.

**Comment by DeadLord1337** [comment]
My virus update `(4.55 - 4.55) + 3.885` it is the best value 100 % identical to vanilla. Can not touch Virus.js, better physics split fix

**Comment by Agarian** [comment]
Setting `exp` to `Math.random() * (4.6 - 4.55) + 3.885;` seems to look quite vanilla IMO.

**Comment by AlexHGaming** [comment]
@Agarian > I can't help but think that the number should be 3.885, not 4. And I'm pretty sure that (4.55 - 4.55) cancels its self out. I mean, (4.55 - 4.55) + 3.885 pretty much says 0 + 3.885.

which is why i made the pr xD

**Comment by AlexHGaming** [comment]
@Agarian 
> Setting exp to Math.random() * (4.6 - 4.55) + 3.885; seems to look quite vanilla IMO.

so basically ```javascript
Math.random() * 0.05 + 3.885
```
basically the result will be extremely close to 3.885

**Comment by Agarian** [comment]
That doesn't change that fact that I think you should remove the `(4.55 - 4.55);`.

**Comment by AlexHGaming** [comment]
I force you @Fan7asy! Merge PR!

**Comment by Luka967** [comment]
I like how nobody's still looked at MultiOgar's popped cells having perfect 2x scaling.

**Comment by AlexHGaming** [comment]
@Luka967 smartass

**Comment by Agarian** [comment]
k

**Comment by Fan7asy** [comment]
I won't merge this because the value should be `3.885` instead of `4`.
`(4.55 - 4.55) + 3.885` does equate to `3.885` after all.

**Pull request closed without merging**
