### PR TITLE
...

### PR DESCRIPTION
**Pull request by AlexHGaming**
idk why i couldnt get to this :p

### CODE REVIEW

**Comment by ArixProject** [comment]
:D

**Comment by Fan7asy** [comment]
Looks good, thanks

**Comment by AlexHGaming** [comment]
@Agarian I don't think there's even a use for it. Shall I PR to remove it?

**Comment by fayizan** [comment]
@AlexHGaming  @Agarian Nope!, multiogar is not only for agario client :|

**Comment by Agarian** [comment]
I mean unless somebody incorporates premium skins in their client, to work the same way they used to in agar.io, or we somehow find a way to make premium skins work in agar.io, that chat command is pretty useless.

**Comment by Agarian** [comment]
Come to think of it, is there a way for premium skins to return/get un-patched? That's probably a stupid question. But maybe via an extension?

**Pull request merged**
