### PR TITLE
Added name argument for Minion Command

### PR DESCRIPTION
**Pull request by KevlarFromDiscord**
This pull request will allow players to change bot names with the /minion command, though it will not change it directly to the Config File/gameserver.ini

Old Usage:
/minion amount = Gives you the XX Amount of Minions
or
/minion amount id = Gives the player the XX Amount of Minions

New Usage:
/minion amount [Name] [Mass] = Gives you the XX Amount of Minions with a new name, if no name is specified, it uses the one on gameserver.ini file

or

/minion amount id [Name] [Mass] = Gives the player the XX Amount of Minions with a new name, if no name is specified, it uses the one on gameserver.ini file

### CODE REVIEW

**Comment by Agarian** [comment]
*If any contributors here are even active anymore*, this looks all good for merging

**Comment by KevlarFromDiscord** [comment]
Hello, if you guys will approve this, approve [#1460](https://github.com/Megabyte918/MultiOgar-Edited/pull/1460)

**Comment by KevlarFromDiscord** [comment]
going to fix arguments again!

**Comment by KevlarFromDiscord** [comment]
this is ready to be pushed to official, don't forget [#1460](https://github.com/Megabyte918/MultiOgar-Edited/pull/1460)

**Comment by FirstCodeReviewer** [comment]
4 commits for that less changes :O

**Comment by KevlarFromDiscord** [comment]
i currently can't code right now, if anyone can fix it thanks, i am away from home

**Comment by KevvyCodes** [comment]
could you transfer this pr to me? i am KevlarFromDiscord

**Comment by KevlarFromDiscord** [comment]
@MastaCoder All done, i'm @KevvyCodes though

**Pull request merged**
