### PR TITLE
Fix for Cigar Skins

### LINKED ISSUE #634: null names !
i'm getting no names or skins when i link my server to a cigar client ! 
image
http://omar-me.ga 
i also tried a client that looks like agarplus still nulls

### PR DESCRIPTION
**Pull request by Tyler3D**
Fixes #634 
1. Skin with Brackets now work on Cigar
2. And vice versa

### CODE REVIEW

**Comment by Tyler3D** [comment]
Resolves #625 too

**Comment by Megabyte918** [comment]
@Tyler3D Wouldn't
`writer1.writeStringZeroUtf8("%" + skin);`
Be the same as doing `skinName = "%" + inner;`?

**Comment by Tyler3D** [comment]
@Megabyte918 Clients are weird. Agar.io wants skins sent as %skinname while most other clients use just the skinname

**Comment by Tyler3D** [comment]
The server needs to send %skinname for protocol 11 and just the skinname for other protocols.

**Comment by Megabyte918** [comment]
@Tyler3D Thanks

**Comment by Tyler3D** [comment]
@Megabyte918 Your welcome

**Pull request merged**
