### PR TITLE
Removes errors and makes more 'understandable'

### PR DESCRIPTION
**Pull request by AlexHGaming**

### CODE REVIEW

**Comment by MastaCoder** [comment]
These changes don't really make sense. You're adding more variables to be used if we do that. What errors do you get right now..?

**Comment by AlexHGaming** [comment]
@MastaCoder on the small splits, it said that the angle was used out of scope, with a yellow line under the word.

**Comment by AlexHGaming** [comment]
so it got rid of that yellow line.

**Comment by gyeyoqu** [comment]
mm unnecesary?

**Comment by AlexHGaming** [comment]
Well it's better fixing an error than there is an error ¯\_(ツ)_/¯

**Comment by AlexHGaming** [comment]
Closing, old PR and no-one bothering.

**Pull request closed without merging**
