### PR TITLE
Finished Auto-Restart

### PR DESCRIPTION
**Pull request by Tyler3D**
Restart command and auto-restart every day. Obviously not from OgarUL XD. Anyway, I don't know linux so, can't do the shell script. The restart won't work unless you use the win-Start.bat.

### CODE REVIEW

**Comment by Gimmo** [comment]
Why you try include OS tasks to MultiOgar? You absolutely don't know what OS is for and how it works? This kind of prosthesis eats a lot of resources and try to replace good, small, fast and already installed OS utilities working independently, by slow, bad tested duplicates. Learn linux instead of try to rewrite it with javascript.

**Comment by MastaCoder** [comment]
I agree with @Gimmo. There were already 2 pull requests sent in for this #148 #149. We came to a conclusion that this isn't needed because it can be done with node modules or cron jobs.

**Comment by Megabyte918** [comment]
Sorry @Tyler3D, but @Gimmo and @MastaCoder are right. We don't need this.

**Comment by Megabyte918** [comment]
closing..

**Pull request closed without merging**
