### PR TITLE
Fix Protocol issue

### PR DESCRIPTION
**Pull request by AlexHGaming**
#1323 #1324

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Cowpits said to do this, so I did. Anymore PR'ing I will do.

**Comment by Luka967** [comment]
Resolve #1325 while you're at it

**Comment by AlexHGaming** [comment]
I don't understand what I need to fix/adc.

**Comment by Fan7asy** [comment]
I didn't see this PR before I added my latest changes, my bad.

**Pull request closed without merging**
