### PR TITLE
Packet 160 Support

### PR DESCRIPTION
**Pull request by Tyler3D**
Only the arrow. The leaderboard kills my mind

### CODE REVIEW

**Comment by chewydev** [comment]
Is this for the party system? If so, how would we use this?

**Comment by MastaCoder** [comment]
Anybody confirm working?

**Comment by AlexHGaming** [comment]
@MastaCoder @Tyler3D Not confirmed.
image

**Comment by Flavorounet** [comment]
Hi, i have an error too for this update, see there the error :
[http://vpictu.re/uploads/3670983680abd2c2fe0811dd34ea1cbe33a78548.png](url)

**Comment by Megabyte918** [comment]
Closing for now.

**Pull request closed without merging**
