### PR TITLE
Popsplit Macro

### PR DESCRIPTION
**Pull request by Tyler3D**
For the lazy and stereotypical Americans. I'm talking to you @Tyler3D

### CODE REVIEW

**Comment by Agarian** [comment]
Bro, this is already existant in the macro

**Comment by Tyler3D** [comment]
@Agarian Ik but A slower double split will increase the chance of a popsplit. This is about slow enough

**Comment by Tyler3D** [comment]
I was going to change that but I guess a fast one could be useful along with a slow one.

**Comment by Agarian** [comment]
I'll admit, you got me there, but there's an issue
https://github.com/Tyler3D/MultiOgar-Edited/blob/940bd153d2eee25e6b551581cd602c0068b0eb6f/src/scripts/AgarMacros.js#L80

**Comment by Tyler3D** [comment]
@Agarian Should I remove space macro or use another letter for popsplits?

**Comment by Megabyte918** [comment]
Can't you just split slower lol

**Comment by Tyler3D** [comment]
america!!!

**Comment by Luka967** [comment]
@Tyler3D you're gonna destroy the american dream

**Comment by Tyler3D** [comment]
xD

**Comment by Megabyte918** [comment]
I don't know mate, removing two other macros for a slower version of an existing one doesn't seem worth it to me

**Comment by Tyler3D** [comment]
@Megabyte918 The ones I removed are basically hotkeys. But, I'll change it if you want.

**Comment by Megabyte918** [comment]
@Tyler3D You mind making this to the updates branch?. I'm planning on rewriting the script to the same branch, add new macros, refactor, etc after i merge this, i don't want it to cause conflicts.

**Comment by Tyler3D** [comment]
@Megabyte918 I thought is already for the updates branch. Apperently I don't know how to github

**Pull request closed without merging**
