### PR TITLE
Protocol 13

### LINKED ISSUE #701: new update? connecting

### PR DESCRIPTION
**Pull request by Tyler3D**
Fixes #701 
Lets you join

### CODE REVIEW

**Comment by Jhair2015** [comment]
I thought it was something more complicated xD

**Comment by imnotNxhz1** [comment]
@Tyler3D love U ♥ :) xD

**Comment by Tyler3D** [comment]
@Jhair2015 It would be if miniclip did something crazy. But I think the leaderboard only needs fixing

**Comment by Tyler3D** [comment]
Protocol 7,9,11,13 are pretty similar

**Comment by Tyler3D** [comment]
Protocol 13 adds a "minimap" in party mode. It may be required to add the packets to Multi-Ogar-Edited if a gamemode id equals the party gamemode id which is 8 I think. Correct me if I'm wrong.

**Comment by Megabyte918** [comment]
@Tyler3D Thanks mate
Also I couldn't see a minimap lol, was I too late?

**Comment by Tyler3D** [comment]
@Megabyte918 There is a arrow pointing to your teammate if someone else joins your same party with the same token.

**Comment by Megabyte918** [comment]
Ohh

**Comment by Agarian** [comment]
Interesting

**Pull request merged**
