### PR TITLE
Small refractors, add feature

### PR DESCRIPTION
**Pull request by Agarian**
- If ``playerDisconnectTime`` is less than 0, then don't remove the cells.

### CODE REVIEW

**Comment by Jhair2015** [comment]
But does it leave the cell color gray or normal?

**Comment by AlexHGaming** [comment]
@Jhair2015 Normal.

**Comment by ZfsrGhS953** [comment]
Refractors... Agar.io doesn't have refracting telescopes.

**Comment by Luka967** [comment]
xD

**Comment by Agarian** [comment]
xd

**Pull request merged**
