### PR TITLE
Make a new config setting

### PR DESCRIPTION
**Pull request by AlexHGaming**
Cuz why not :P

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Ignore top 3, they wont do anything.

**Comment by Fan7asy** [comment]
There are complications please  fix them

**Comment by AlexHGaming** [comment]
@Fan7asy Examples?

**Comment by AlexHGaming** [comment]
ahh, i see why

**Comment by AlexHGaming** [comment]
Let me try and fix this.

**Pull request closed without merging**
