### PR TITLE
Press Q to make minions collect pellets (can be disabled in config)

### PR DESCRIPTION
**Pull request by ZfsrGhS953**

### CODE REVIEW

**Comment by Megabyte918** [comment]
@ZfsrGhS953 Thanks for taking the time to work on this, I couldn't figure out how to do it for the life of me! Let me know when it's ready for merge :)

**Comment by Fantasy-Agario** [comment]
Wow this is amazing XD @ZfsrGhS953

**Comment by AlexandriteErikParacelsus** [comment]
Holy crap dude, you are a geinus @ZfsrGhS953 you're the best m9

**Comment by t11tanYT** [comment]
pellet mode created?

**Comment by ZfsrGhS953** [comment]
It was already ready for merging when this PR was created. When I said "preparing my pull request" I meant that I was uploading files to my fork from my PC. I only created the pull request after I did that, so it's ready .

**Comment by Jhair2015** [comment]
:D omg

**Comment by Fantasy-Agario** [comment]
Merged ! :D @ZfsrGhS953 @Megabyte918

**Pull request merged**
