### PR TITLE
Added Mass Argument to Function

### PR DESCRIPTION
**Pull request by KevlarFromDiscord**
This will help the Pull Request [#1458](https://github.com/Megabyte918/MultiOgar-Edited/pull/1458) on the new Mass Argument placed there

### CODE REVIEW

**Comment by B0RYS** [comment]
@KevlarFromDiscord can you make your changes on the latest commit please?

**Comment by KevvyCodes** [comment]
@B0RYS if possible, please commit this, pr #1458 won't work without this

**Comment by B0RYS** [comment]
@KevvyCodes The entire file's been changed in the latest version so this is obsolete now. Sorry.

**Comment by KevvyCodes** [comment]
ok

**Comment by B0RYS** [comment]
I've also made some changes on my local files. I'll push my changes sometime today.

**Pull request closed without merging**
