### PR TITLE
wtf error

### PR DESCRIPTION
**Pull request by DeadLord1337**

### CODE REVIEW

**Comment by AlexHGaming** [comment]
@DeadLord1337 yes, i really happy for a merge.

**Comment by DeadLord1337** [comment]
it's not the vanilla!! :с

**Comment by Luka967** [comment]
Shit I forgot to change this config when committing
@Fan7asy

**Comment by Fan7asy** [comment]
L33ts simplify th1s

**Comment by Fan7asy** [comment]
Fixed in 44407f2a25b1fd8ed9c83ef07436538c19e330b9

**Pull request closed without merging**
