### PR TITLE
Web console

### PR DESCRIPTION
**Pull request by Gimmo**
At first glance it's look like working.

Changed MO files - CommandList.js : 
changed column order in playerList , because table was messed up in utf8 terminals by "cool names" ; console.log changed to  Logger.print for consistance.

New files:   
src/console-plus.js
src/console-plus.html

Specific terminal commands:

arrow Up/Dn         -> comands history for current session
arrow Left          -> clean input line
Esc or "logout"     -> terminal logout

default login/pass  ->  "admin" "pass"
address of server   ->  console-plus.html :: 24
port                ->  console-plus.js :: 135

run "node console-plus.js" with your favorite daemonizer, it will start MO. 
Play the game as usually.
To open console go yourserver:1234 in browser. 

run.sh should be removed - it's present by mistake

### CODE REVIEW

**Comment by MastaCoder** [comment]
Ehhhhhhhhhhhhhhhh. Feels a lot more like just extra code, if we have the terminal this isn't that useful.

**Comment by Gimmo** [comment]
@MastaCoder  What terminal do you have when your server run as a daemon? 

If you don't need web terminal you have just run MO the old way. 
Console-plus doesn't change code of server, it's just extension. Wrapper. 

@Tyler3D  Have you ever heard about VM box? It's address of virtual box, yes, on my pc. You are free to change it to whatever you need, just read my initial comment.

**Comment by Megabyte918** [comment]
@Gimmo Thanks so much, it works great! However there are a few things here and there that I have found: 

1) When running console-plus for the first time, It installs all of the modules that it needs, except for Websocket. It throws an error until you install it manually through npm.

2) It breaks the regular terminal, once you start the server using console-plus, you will be disconnected from the normal terminal, you cannot enter commands, you can't backspace, you can't do anything.  However the web console works fine. Is this supposed to happen? Are you only supposed to use the web terminal if you start the server with console-plus? I'm using Win10 to test by the way.

**Comment by Tyler3D** [comment]
@Gimmo But, keeping localhost as default would me better. I don't have that IP. And I have 20 virtual machines.

**Comment by Tyler3D** [comment]
@Megabyte918 On C9 you said your going to use another version. Can you give me a link?

**Comment by Gimmo** [comment]
@Megabyte918  
1. I'll try to look this later, thank you . 
2. It's supposed to be. May be some warnind message should be done.... Terminal should be inaccessible at all, but a part of functions (commands) can be reborn, if you need, by uncomment pipeline at line 144 console-plus.js . But I, rather, will try to block it completely on OS reasons - I don't like uncontrolled streams on daemon. Them should be strictly redirected to /dev/null . 

I, personally, preferre to implement web-console into MO, as it, in current state, eats some more resources then I like.    

Thank you for kind words.

**Comment by Gimmo** [comment]
Websocket module changed to ws. No additional dependences now.

**Comment by Megabyte918** [comment]
@Gimmo Works perfectly 👍

**Pull request merged**
