### PR TITLE
Fixes #812 and fixes typo

### LINKED ISSUE #812: Server crash bug
I just added the recent commits to my MultiOgar-Edited servers and for some reason the Experimental server crashed. 

I suspect the issue lies within the Experimental gamemode, because switching the serverGamemode (gameserver.ini) from Experimental to Teams (or any other gamemodes), seems to resolve the issue. All the other gamemodes works, except Experimental (not sure why).

Crash message:
[FATAL] TypeError: Cannot read property 'clone' of undefined
    at GameServer.mainLoop.movingNodes.forEach.GameServer.willCollide (/root/Experimental/src/GameServer.js:900:26)
    at Mode.Experimental.spawnMotherCell (/root/Experimental/src/gamemodes/Experimental.js:35:21)
    at Mode.Experimental.onTick (/root/Experimental/src/gamemodes/Experimental.js:65:14)
    at GameServer.mainLoop.movingNodes.forEach.nodesPlayer.forEach [as mainLoop] (/root/Experimental/src/GameServer.js:647:23)
    at Timer.listOnTimeout (timers.js:92:15)

Screenshot: https://i.gyazo.com/dc39266b76711d4b284b94d9543146fb.png

### PR DESCRIPTION
**Pull request by AlexHGaming**
#812

### CODE REVIEW

**Comment by AlexHGaming** [comment]
Ignore top 2 bits. The last README brings it back to what it was, but fixes typo.

**Comment by AlexHGaming** [comment]
Same to #817

**Comment by Agarian** [comment]
@AlexHGaming Conflicts

**Comment by MastaCoder** [comment]
^

**Comment by MastaCoder** [comment]
Oops

**Comment by Luka967** [comment]
Why reverse the `playerCells` array twice? Doing that won't change the array at all.

**Comment by AlexHGaming** [comment]
@Luka967 Oh lol, doing it twice makes it change for me. Idk if my brain is smart
reverting

**Comment by MastaCoder** [comment]
Delete the repo and re-push everything, too many false commits ;-;

**Comment by AlexHGaming** [comment]
oh kk
ill make a new one

**Comment by Agarian** [comment]
@Luka967 What happens if it reverses once?

**Comment by Luka967** [comment]
@Agarian Obviously enough the array's element order gets reversed.
```js
> [ 1, 2, 3, 4 ].reverse()
[ 4, 3, 2, 1 ]
> [ { id: 213 }, { id: 411 }, { id: 210 } ].reverse()
[ { id: 62 }, { id: 210 }, { id: 411 } ]
```

**Comment by MastaCoder** [comment]
So https://github.com/Megabyte918/MultiOgar-Edited/pull/816/commits/4e3a5eb7d532cc5be8bdcc3690644e7437fb553d is useless.

**Pull request closed without merging**
