### PR TITLE
Add killall command

### PR DESCRIPTION
**Pull request by AlexHGaming**
Useless commits - R.I.P Fantasy's hand after all of the clicking he has to do.
Meh, I felt like adding this after the awareness thanks to @cowpits :)

### CODE REVIEW

**Comment by ZfsrGhS953** [comment]
@AlexHGaming What editor do you use? I use Notepad++, it adds tabs automatically.

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 Visual Studio Code 2017

**Comment by AlexHGaming** [comment]
@ZfsrGhS953 but with this, it was the github editor, all it was, was just copy and paste out the code of VSC, then put it in the github, add the writeline & shit & done XD

**Comment by cowpits** [comment]
what mess have I gotten myself into now? 
thanks for the commit @AlexHGaming you rock and you helped me sort out the duh moment i had lol.

**Comment by AlexHGaming** [comment]
@cowpits haha no problem man remember you have my discord when you need me.

**Comment by Fan7asy** [comment]
@AlexHGaming Instead of copying and pasting the code into github, use git.

**Comment by AlexHGaming** [comment]
🤔

**Pull request merged**
