### PR TITLE
HungerGames/Tournament gamemodes and Fixes Gamemodes

### PR DESCRIPTION
**Pull request by pabloalber84**
The gamemodes have a things needless (Like: Logger requires or Entity's requires), this fix this simple issues.

The HungerGames gamemode and Tournament gamemode not working in MultiOgar-Edited because the tick counter issue.

Explain:
The HungerGames take a leaderboard update for timer.
At begging of the start gamemode, HungerGames set `gameServer.run = false;` to players don't get moved from the Established position, and in the MainLoop of GameServer.js, to update the leaderboard (Needed to Tournament base gamemode timer), the leaderboard needs the condition `if (((this.tickCounter + 7) % 25) === 0)`, but, the variable tickCounter, IS ADDED IN the condition `if (this.run)`, this causes to the variable tickCounter don't get `this.tickCounter++;`, and if tickCounter don't get added one more, the leaderboard can't meet the condition, this are the bug from HungerGames and Tournament Gamemodes.

But, why is needed to add condition `this.gameMode.IsTournament`?
To detect if are tournament, and, if are, add a tick, because, if I add the tickCounter out of condition of `this.run`, this can call functions unnecessarily without players (In case of others Gamemodes, like FFA, Experimental....)

I have the correct positions from HungerGames, but, I hope people will at least try a little to do it for themselves.

### CODE REVIEW

**Comment by MastaCoder** [comment]
Can anyone confirm this working.

**Comment by Wair1o17** [comment]
Has trouble joining the game

**Comment by pabloalber84** [comment]
@Wair1o17 If you say about the spawn positions, I say: 

> I have the correct positions from HungerGames, but, I hope people will at least try a little to do it for themselves.

If can see "Waiting for players: 0/0", is working.

**Comment by OfficialKake** [comment]
I got a Fatal error whit the GameServer.js

**Comment by pabloalber84** [comment]
@OfficialKake Can you send the fatal error?

**Comment by OfficialKake** [comment]
yes, here is it
http://imgur.com/a/UBNoH

**Comment by pabloalber84** [comment]
Fixed.

**Comment by fayizan** [comment]
I m stuck at this undefined

screenshot_147

**Comment by pabloalber84** [comment]
Oh im sorry, I forgot put the gameserver configs to tournament.
Fixed.

**Comment by Gharyfb258** [comment]
@pabloalber84 
image

Another error :/

**Comment by Gharyfb258** [comment]
Another error

`>| [FATAL] TypeError: node.getType is not a function
    at HungerGames.onPlayerDeath (C:\Users\Gino\Desktop\HungerGames\s
rc\gamemodes\HungerGames.js:102:30)
    at HungerGames.Tournament.onCellRemove (C:\Users\Gino\Desktop\Hun
gerGames\src\gamemodes\Tournament.js:172:18)
    at PlayerCell.onRemove (C:\Users\Gino\Desktop\HungerGames\src\ent
ity\PlayerCell.js:41:25)
    at GameServer.removeNode (C:\Users\Gino\Desktop\HungerGames\src\G
ameServer.js:410:10)
    at GameServer.resolveCollision (C:\Users\Gino\Desktop\HungerGames
\src\GameServer.js:780:10)
    at eatCollisions.forEach (C:\Users\Gino\Desktop\HungerGames\src\G
ameServer.js:598:18)
    at Array.forEach (native)
    at GameServer.mainLoop (C:\Users\Gino\Desktop\HungerGames\src\Gam
eServer.js:597:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)`

**Comment by pabloalber84** [comment]
Fixed :B Idk why this function are here :v

**Comment by Gharyfb258** [comment]
:v

**Comment by NoiseControllers** [comment]
[Error]
http://i.imgur.com/VDmOydg.png
it is produced When the game ends

**Comment by OfficialKake** [comment]
the hunger games mode is 5?

**Comment by NoiseControllers** [comment]
@OfficialKake yes

**Comment by OfficialKake** [comment]
@NoiseControllers 
yeah, i have same error

**Comment by pabloalber84** [comment]
Fixed

**Comment by OfficialKake** [comment]
thx, but i still have a new problem, that generates some players outside of the map

**Comment by OfficialKake** [comment]
when finishes the round, pauses the game
http://imgur.com/a/CzZpo
and other, that appears some big mass outside of the map

**Comment by pabloalber84** [comment]
@OfficialKake idk why pause for you, the script are written to exit the process, and for the big mass outside of the map: I already say: 

> I have the correct positions from HungerGames, but, I hope people will at least try a little to do it for themselves.
Do it yourself.

@NoiseControllers you need run with forever :B

**Comment by OfficialKake** [comment]
@pabloalber84 thx

**Comment by fayizan** [comment]
the game counts the player as in even the player left tournament

**Comment by Gigabyte918** [comment]
i already have hunger games and tournament for my server Multi Ogar

**Comment by pabloalber84** [comment]
@fayizan Yeah, onServerInit gamemode have:
`gameServer.config.playerDisconnectTime = 10; // So that people dont disconnect and stall the game for too long`
You can remove the line.

**Comment by fayizan** [comment]
@pabloalber84 you mean `this.dcTime` ?

**Comment by pabloalber84** [comment]
No @fayizan in the gamemode, search the `gameServer.config.playerDisconnectTime = 10;` and delete the line :B

**Comment by fayizan** [comment]
I deleted the line but it still count the player

**Comment by pabloalber84** [comment]
@fayizan you added correct all comits? the comits have fixes, if still count the player, this dont pass by in the function onCellRemove from gamemode.

**Comment by fayizan** [comment]
@pabloalber84 I git clone from your fork and modified too but still unnamed cells

**Comment by pabloalber84** [comment]
Can't be possible, you added a bot? if is a bot, count to player.

**Comment by fayizan** [comment]
ok Its working, I reinstalled from fork again. 
I Removed the line `gameServer.config.playerDisconnectTime = 0;` and didnt touch anything at gameserver.ini but  I think something is conflicting by changing settings in gameserver.ini

**Comment by pabloalber84** [comment]
@fayizan Yeah, possible.

**Comment by fayizan** [comment]
@MastaCoder Merge this ?

**Comment by Agarian** [comment]
Hello. I am to inactive.

**Comment by MastaCoder** [comment]
Is everything confirmed working?

**Comment by pabloalber84** [comment]
@MastaCoder some people confirmed, but, the positions is on the part of the same users to do it.

**Comment by fayizan** [comment]
Yup Working Fine for me  :) thanks @pabloalber84

**Comment by MastaCoder** [comment]
👍

**Comment by Agarian** [comment]
And there we have it

**Pull request merged**
