### PR TITLE
Better Collect

### PR DESCRIPTION
**Pull request by DeadLord1337**

### CODE REVIEW

**Comment by CodeFlush** [comment]
Better What Please provide more details @DeadLord1337

**Comment by AlexHGaming** [comment]
@DeadLord1337 this is dead useless. What are you trying to do with it

**Comment by DeadLord1337** [comment]
minion better collect a lot believe me

**Comment by CodeFlush** [comment]
The "P" key has never worked for me...

**Comment by ZfsrGhS953** [comment]
@DeadLord1337 What this is doing is resetting the visible cells array only every 10th time. This will cause weird behavior and performance issues.

**Comment by Fan7asy** [comment]
^

**Pull request closed without merging**
